# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kintai < Formula
  desc "Generates the URL link in various formats"
  homepage "https://github.com/takuabonn/kintai"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/takuabonn/kintai/releases/download/v0.1.6/kintai_0.1.6_Darwin_x86_64.tar.gz"
      sha256 "d75de322bd58324a27a495e843daa6f539643f891b2abee8813fa71ff7718e42"

      def install
        bin.install "kintai"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/takuabonn/kintai/releases/download/v0.1.6/kintai_0.1.6_Darwin_arm64.tar.gz"
      sha256 "89d72db60d6310c502f7646eb315f5845728c9491aa3622f7aadb67102e0d660"

      def install
        bin.install "kintai"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/takuabonn/kintai/releases/download/v0.1.6/kintai_0.1.6_Linux_arm64.tar.gz"
      sha256 "6ab8d5e58b5a63c49cf00174ad6fd670f421b1f6c95899162f2f32525ba77e57"

      def install
        bin.install "kintai"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/takuabonn/kintai/releases/download/v0.1.6/kintai_0.1.6_Linux_x86_64.tar.gz"
      sha256 "d69cf4cb487c7e0718fc58333c47fd2393519bdfe06467ae208b3c46a017d84e"

      def install
        bin.install "kintai"
      end
    end
  end
end
